Repository VowpalWabbit/vowpal_wabbit, pull requests merged in 2019-03, with the labels that each got.

#1770 [CCB] Enable interactions to be overridden by an example
  vowpalwabbit/example.h
  vowpalwabbit/gd.h
Labels: CCB

#1761 [CCB] Add ccb_explore_adf reduction
  vowpalwabbit/conditional_contextual_bandit.cc
  vowpalwabbit/conditional_contextual_bandit.h
  vowpalwabbit/global_data.h
  vowpalwabbit/learner.h
  vowpalwabbit/parse_args.cc
Labels: CCB

#1767 [CCB] Dsjson and json parsing for CCB
  cs/unittest/TestJson.cs
  test/unit_test/CMakeLists.txt
  test/unit_test/ccb_parser_test.cc
  test/unit_test/dsjson_parser_test.cc
  test/unit_test/json_parser_test.cc
  test/unit_test/test_common.h
  test/unit_test/unit_test.vcxproj
  test/unit_test/unit_test.vcxproj.filters
  vowpalwabbit/parse_example_json.h
  vowpalwabbit/parser.cc
Labels: CCB

#1797 Sample from PDF and swap chosen as part of CCB
  test/RunTests
  test/pred-sets/ref/cb_sample_seed.predict
  test/test-sets/cb_sample_seed.data
  test/unit_test/ccb_parser_test.cc
  vowpalwabbit/CMakeLists.txt
  vowpalwabbit/cb_sample.cc
  vowpalwabbit/cb_sample.h
  vowpalwabbit/conditional_contextual_bandit.cc
  vowpalwabbit/parse_args.cc
  vowpalwabbit/vw_core.vcxproj
Labels: CCB

#1805 Extend CCB parser for Dsjson/Json to support implicitly converting CB examples to CCB examples
  test/unit_test/ccb_parser_test.cc
  test/unit_test/dsjson_parser_test.cc
  test/unit_test/json_parser_test.cc
  vowpalwabbit/parse_example_json.h
Labels: CCB

#1795 Implement finish example and output for CCB
  vowpalwabbit/cb_algs.h
  vowpalwabbit/conditional_contextual_bandit.cc
Labels: CCB

#1796 Shared example decision feature injection and auto crossing
  vowpalwabbit/conditional_contextual_bandit.cc
  vowpalwabbit/example.h
Labels: CCB

#1790 Add example C# Simulator
  .scripts/restore.cmd
  cs/examples/simulator/App.config
  cs/examples/simulator/Program.cs
  cs/examples/simulator/Properties/AssemblyInfo.cs
  cs/examples/simulator/VowpalWabbitSimulator.cs
  cs/examples/simulator/packages.config
  cs/examples/simulator/simulator.csproj
  vowpalwabbit/vw.sln
Labels: Lang: C#

#1809 Enable JSON example parsing in Python bindings
  python/pylibvw.cc
  python/vowpalwabbit/pyvw.py
  vowpalwabbit/parse_example.cc
  vowpalwabbit/parse_example.h
  vowpalwabbit/parse_example_json.h
  vowpalwabbit/parser.cc
  vowpalwabbit/parser.h
Labels: Lang: Python
